artists/urls.py
from django.conf.urls import url
from artists import views

uuid_match = r'(?P<uuid>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})'

urlpatterns = [
    url(r'^genres$', views.genres, name='artists-genres'),
    url(r'^genre/(?P<genre_id>\d+)$', views.genre, name='artists-genre'),
    url(r'^search$', views.search, name='artists-search'),
    url(r'^artist/%s$' % (uuid_match), views.artist, name='artists-artist'),
]

fonil-web/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import artists.views

urlpatterns = [
    url(r'^$', artists.views.main, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^artists/', include('artists.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

artists/models.py
import uuid
from django.db import models
from django.conf import settings


class Genre(models.Model):
    name = models.CharField(max_length=254)

    class Meta:
        ordering = ["name"]

class Artist(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=254)
    fbid = models.CharField(max_length=254)
    description = models.TextField(max_length=3000, blank=True, null=True)
    location = models.CharField(max_length=254, blank=True, null=True)
    hometown = models.CharField(max_length=254, blank=True, null=True)
    followers = models.IntegerField(blank=True, null=True)
    website = models.CharField(max_length=254, blank=True, null=True)
    fb_link = models.CharField(max_length=254, blank=True, null=True)
    twitter_link = models.CharField(max_length=254, blank=True, null=True)
    soundcloud_link = models.CharField(max_length=254, blank=True, null=True)
    bandcamp_link = models.CharField(max_length=254, blank=True, null=True)
    spotify_link = models.CharField(max_length=254, blank=True, null=True)
    youtube_link = models.CharField(max_length=254, blank=True, null=True)
    image = models.CharField(max_length=254, blank=True, null=True)
    genres = models.ManyToManyField(Genre)
    similar = models.ManyToManyField('Artist')
    date = models.DateTimeField(auto_now=True)

LINK_CHOICES = (
        ('yt', 'Youtube'),
        ('sf', 'Spotify'),
        ('sc', 'Soundcloud'),
)

class Link(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    url = models.CharField(max_length=254)
    link_type = models.CharField(max_length=2, choices=LINK_CHOICES)
    name = models.CharField(max_length=254, blank=True, null=True)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    user_name = models.CharField(max_length=50, blank=True)
    comment = models.TextField(max_length=3000)

    submit_date = models.DateTimeField(default=None, db_index=True)

class Post(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    url = models.CharField(max_length=254)
    text = models.TextField(max_length=3000, blank=True, null=True)
    date = models.DateTimeField()

artists/views.py
from django.shortcuts import render, get_object_or_404
import models

def main(request):
    artists = models.Artist.objects.order_by('?')[:20]

    ret = {
            "artists": artists,
            }
    return render(request, "artists/index.html", ret)

def genres(request):
    genres = models.Genre.objects
    artists = models.Artist.objects
    ret = {
            "artists": artists,
            "genres": genres,
            "all_genres": True
          }
    return render(request, "artists/genres.html", ret)

def genre(request, genre_id):
    genres = models.Genre.objects
    genre = get_object_or_404(models.Genre, pk=genre_id)

    artists = models.Artist.objects.filter(genres__in=[genre])
    ret = {
            "artists": artists,
            "genres": genres,
            "genre": genre
          }
    return render(request, "artists/genres.html", ret)

def search(request):
    query = request.GET.get("q", None)
    artists = models.Artist.objects.filter(name__icontains=query)

    ret = {
            "artists": artists,
            "query": query,
            }
    return render(request, "artists/search.html", ret)

def artist(request, uuid):
    artist = get_object_or_404(models.Artist, uuid=uuid)
    ret = {"artist": artist}
    return render(request, "artists/artist.html", ret)

artists/templates/artists/artist.html
{% extends "artists/base.html" %}

{% block content %}
<section class="vbox" id="bjax-el">
    <section class="scrollable wrapper-lg">
              <div class="row">
                <div class="col-sm-8">
                  <div class="panel wrapper-lg">
                    <div class="row">
                      <div class="col-sm-5">
                        <img src="{{artist.image}}" class="img-full m-b">
                      </div>
                      <div class="col-sm-7">
                        <h2 class="m-t-none text-black">{{ artist.name }}</h2>
                        <div class="clearfix m-b-lg">
                          <div class="clear">
                            <small class="block text-muted">{{artist.followers}} followers</small>
                          </div>
                        </div>
                        <!--<div class="m-b-lg">
                          <a href="#" class="btn btn-info">Play</a> <a href="#" class="btn btn-default">3 Comments</a>
                          </div>-->
                        <div>
                          {% if artist.genres.all %}Genres:
                            {% for genre in artist.genres.all %}
                            <a href="{% url "artists-genre" genre.id %}" class="badge bg-light">{{genre.name}}</a> 
                            {% endfor %}
                          {%endif%}
                        </div>
                      </div>
                    </div>
                    <div class="m-t">
                      {% if artist.description %}
                      <p>{{artist.description}}</p>
                      {%endif%}
                    </div>
                    <h4 class="m-t-lg m-b">Links</h4>
                    {% for link in artist.link_set.all %}
                    <ul class="list-group list-group-lg">
                      <li class="list-group-item">
                        <a href="{{link.url}}" class="m-r-sm pull-left" target="_blank">
                          <i class="icon-control-play text"></i>
                          <i class="icon-control-pause text-active"></i>
                        </a>
                        <div class="clear text-ellipsis">
                          <span>{{link.name}}</span>
                          <span class="text-muted"> </span>
                        </div>
                      </li> 
                    </ul>
                    {% endfor%}
                  </div>
                </div>
                <div class="col-sm-4">
                  <div class="panel panel-default">
                    <div class="panel-heading">Suggestions</div>
                    <div class="panel-body">
                      {% for similar in artist.similar.all %}
                      <article class="media">
                        <a href="{% url 'artists-artist' similar.uuid %}" class="pull-left thumb-md m-t-xs">
                          <img src="{{similar.image}}">
                        </a>
                        <div class="media-body">                        
                          <a href="{% url 'artists-artist' similar.uuid %}" class="font-semibold">{{ similar.name }}</a>
                        </div>
                      </article>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
            </section>
        </section>
{% endblock %}

artists/templates/artists/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en" class="app">
<head>  
  <meta charset="utf-8" />
  <title>Musik | Web Application</title>
  <meta name="description" content="app, web app, responsive, admin dashboard, admin, flat, flat ui, ui kit, off screen nav" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <link rel="stylesheet" href="{% static 'js/jPlayer/jplayer.flat.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/animate.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/font.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/app.css' %}" type="text/css" />  
    <!--[if lt IE 9]>
    <script src="js/ie/html5shiv.js"></script>
    <script src="js/ie/respond.min.js"></script>
    <script src="js/ie/excanvas.js"></script>
  <![endif]-->
  {% block extra-head %}
  {% endblock %}
</head>
<body class="">
  <section class="vbox">
    <header class="bg-white-only header header-md navbar navbar-fixed-top-xs">
      <div class="navbar-header aside bg-info dk nav-xs">
        <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen,open" data-target="#nav,html">
          <i class="icon-list"></i>
        </a>
        <a href="{% url "home" %}" class="navbar-brand text-lt">
          <i class="icon-earphones"></i>
          <img src="images/logo.png" alt="." class="hide">
          <span class="hidden-nav-xs m-l-sm">Musik</span>
        </a>
        <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".user">
          <i class="icon-settings"></i>
        </a>
      </div>      <ul class="nav navbar-nav hidden-xs">
        <li>
          <a href="#nav,.navbar-header" data-toggle="class:nav-xs,nav-xs" class="text-muted">
            <i class="fa fa-indent text"></i>
            <i class="fa fa-dedent text-active"></i>
          </a>
        </li>
      </ul>
      <form class="navbar-form navbar-left input-s-lg m-t m-l-n-xs hidden-xs" role="search" action="{% url "artists-search" %}">
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-btn">
              <button type="submit" class="btn btn-sm bg-white btn-icon rounded"><i class="fa fa-search"></i></button>
            </span>
            <input type="text" name="q" class="form-control input-sm no-border rounded" placeholder="Search songs, albums..." value="{{query}}">
          </div>
        </div>
      </form>
      <div class="navbar-right ">
        <ul class="nav navbar-nav m-n hidden-xs nav-user user">
        </ul>
      </div>      
    </header>
    <section>
      <section class="hbox stretch">
        <!-- .aside -->
        <aside class="bg-dark dk nav-xs aside hidden-print" id="nav">          
          <section class="vbox">
            <section class="w-f-md scrollable">
              <div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="10px" data-railOpacity="0.2">
                


                <!-- nav -->                 
                <nav class="nav-primary hidden-xs">
                  <ul class="nav bg clearfix">
                    <li>
                      <a href="{% url "artists-genres" %}">
                        <i class="icon-music-tone-alt icon  "></i>
                        <span class="font-bold">Genres</span>
                      </a>
                    </li>
                  </ul>
                </nav>
                <!-- / nav -->
              </div>
            </section>
            
            <footer class="footer hidden-xs no-padder text-center-nav-xs">
              <div class="bg hidden-xs ">
              </div>            
            </footer>
          </section>
        </aside>
        <!-- /.aside -->
        <section id="content">
              {% block content%}
              {% endblock %}
          <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen,open" data-target="#nav,html"></a>
        </section>
      </section>
    </section>    
  </section>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <!-- App -->
  <script src="{% static 'js/app.js' %}"></script>  
  <script src="{% static 'js/slimscroll/jquery.slimscroll.min.js' %}"></script>
  <script src="{% static 'js/app.plugin.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jPlayer/jquery.jplayer.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jPlayer/add-on/jplayer.playlist.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jPlayer/demo.js' %}"></script>
</body>
</html>

artists/templates/artists/genres.html
{% extends "artists/base.html" %}

{% block content %}
<section class="vbox" >
  <section class="w-f-md" id="bjax-target">
      <section class="hbox stretch">
             <!-- side content -->
                <aside class="aside bg-light dk" id="sidebar">
                  <section class="vbox animated fadeInUp">
                    <section class="scrollable hover">
                      <div class="list-group no-radius no-border no-bg m-t-n-xxs m-b-none auto">
                        <a href="{% url "artists-genres" %}" class="list-group-item {% if all_genres %}active{% endif %}">
                          All
                        </a>
                        {% for g in genres.all %}
                        <a href="{% url "artists-genre" g.id %}" class="list-group-item {% if g.id == genre.id %}active{% endif %}">
                            {{g.name}}
                          </a>
                        {% endfor %}
                      </div>
                    </section>
                  </section>
                </aside>
                <!-- / side content -->
                <section>
                  <section class="vbox">
                    <section class="scrollable padder-lg">
                      <h2 class="font-thin m-b">{{genre.name}}</h2>
                      <div class="row row-sm">
                        {% for a in artists.all %}
                        <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                          <div class="item">
                            <div class="pos-rlt">
                              <div class="item-overlay opacity r r-2x bg-black">
                                <div class="center text-center m-t-n">
                                  <a href="{% url 'artists-artist' a.uuid %}"><i class="fa fa-play-circle i-2x"></i></a>
                                </div>
                              </div>
                              <a href="{% url 'artists-artist' a.uuid %}"><img src="{{ a.image }}" alt="" class="r r-2x img-full"></a>
                            </div>
                            <div class="padder-v">
                              <a href="{% url 'artists-artist' a.uuid %}" class="text-ellipsis">{{a.name}}</a>
                            </div>
                          </div>
                        </div>
                        {% endfor %}
                      </div>
                    </section>                    
                  </section>
                </section>
      </section>
  </section>
</section>
{% endblock %}

artists/templates/artists/index.html
{% extends "artists/base.html" %}

{% block content %}
<section class="vbox" >
  <section class="w-f-md" id="bjax-target">
      <section class="hbox stretch">
                <section>
                  <section class="vbox">
                    <section class="scrollable padder-lg">
                     <h2 class="font-thin m-b">Discover <span class="musicbar animate inline m-l-sm" style="width:20px;height:20px">
                        <span class="bar1 a1 bg-primary lter"></span>
                        <span class="bar2 a2 bg-info lt"></span>
                        <span class="bar3 a3 bg-success"></span>
                        <span class="bar4 a4 bg-warning dk"></span>
                        <span class="bar5 a5 bg-danger dker"></span>
                      </span></h2>
                      <div class="row row-sm">
                        {% for a in artists.all %}
                        <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                          <div class="item">
                            <div class="pos-rlt">
                              <div class="item-overlay opacity r r-2x bg-black">
                                <div class="center text-center m-t-n">
                                  <a href="{% url 'artists-artist' a.uuid %}"><i class="fa fa-play-circle i-2x"></i></a>
                                </div>
                              </div>
                              <a href="{% url 'artists-artist' a.uuid %}"><img src="{{ a.image }}" alt="" class="r r-2x img-full"></a>
                            </div>
                            <div class="padder-v">
                              <a href="{% url 'artists-artist' a.uuid %}" class="text-ellipsis">{{a.name}}</a>
                            </div>
                          </div>
                        </div>
                        {% endfor %}
                      </div>
                    </section>                    
                  </section>
                </section>
      </section>
  </section>
</section>
{% endblock %}

artists/templates/artists/search.html
{% extends "artists/base.html" %}

{% block content %}
<section class="vbox" >
  <section class="w-f-md" id="bjax-target">
      <section class="hbox stretch">

<!-- side content -->
                <section>
                  <section class="vbox">
                    <section class="scrollable padder-lg">
                      <h2 class="font-thin m-b">Search: {{query}}</h2>
                      <div class="row row-sm">
                       {% for a in artists.all %}
                        <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                          <div class="item">
                            <div class="pos-rlt">
                              <div class="item-overlay opacity r r-2x bg-black">
                                <div class="center text-center m-t-n">
                                  <a href="{% url 'artists-artist' a.uuid %}"><i class="fa fa-play-circle i-2x"></i></a>
                                </div>
                              </div>
                              <a href="{% url 'artists-artist' a.uuid %}"><img src="{{ a.image }}" alt="" class="r r-2x img-full"></a>
                            </div>
                            <div class="padder-v">
                              <a href="{% url 'artists-artist' a.uuid %}" class="text-ellipsis">{{a.name}}</a>
                            </div>
                          </div>
                        </div>
                        {% endfor %}
                      </div>
                    </section>                    
                  </section>
                </section>
        </section>                    
    </section>
</section>
{% endblock %}